config/routes.rb
Rails.application.routes.draw do
  root 'main#portfolio'
  resources :questionnaires, :posts
  get '/portfolio',   to: 'main#portfolio', as: :portfolio
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  end

  def portfolio
      @displayadtech = "http://displayadtech.com/the_display_advertising_technology_landscape"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    @posts = Post.all
    render layout: 'no-sidebar'
  end

  def new
    @post = Post.new
    render layout: 'no-sidebar'
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'post was successfully destroyed.'
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params 
     params.require(:post).permit(:title, :category, :content, :tags)
    end
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: [:show, :edit, :update, :destroy]

  # GET /questionnaires
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /questionnaires/1
  def show
    @questionnaires = Questionnaire.all
    render layout: 'no-sidebar'
  end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new
    render layout: 'no-sidebar'
  end

  # GET /questionnaires/1/edit
  def edit
  end

  # POST /questionnaires
  def create
    @questionnaire = Questionnaire.new(questionnaire_params)

    if @questionnaire.save
      redirect_to @questionnaire, notice: 'questionnaire was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /questionnaires/1
  def update
    if @questionnaire.update(questionnaire_params)
      redirect_to @questionnaire, notice: 'questionnaire was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /questionnaires/1
  def destroy
    @questionnaire.destroy
    redirect_to questionnaires_url, notice: 'questionnaire was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def questionnaire_params 
     params.require(:questionnaire).permit(
      :company, :invested, :age, :visits_desktop, :visits_mobile,
      :features_visited_1, :features_visited_2, :features_visited_3,
      :features_visited_4, :features_visited_5,  
      :delightful_features_1, :delightful_features_2,
      :delightful_features_3, :delightful_features_4, 
      :delightful_features_5, :annoying_features_1, 
      :annoying_features_2, :annoying_features_3, 
      :annoying_features_4, :annoying_features_5, 
      :feature_requests, :open_feedback)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-nav">
    <div class="vert-nav-line"></div>
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pull-right">
        <li>
          <a href="#">
            Blog
          </a>
        </li>
        <li>
          <%= link_to "Portfolio", portfolio_path %>
        </li>
        <li>
          <a href="#">
            Contact
          </a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/_sidebar.html.erb
<aside>
  <div class="intro-wrapper">
    <div class="intro-message">
      <%= image_tag "dave.png", :class => "dave_pic" %>
      <h3>
        David Christian<br> 
        <small>
          Full Stack Developer | San Francisco
        </small>
      </h3>
      <hr class="intro-divider">
      <ul class="list-inline intro-social-buttons">
        <li>
          <a href="https://twitter.com/DaveChristian87" class="btn btn-default">
            <i class="fa fa-twitter fa-fw"></i> 
            <span class="network-name">
              Twitter
            </span>
          </a>
        </li>
        <li>
          <a href="https://github.com/DWC01" class="btn btn-default">
            <i class="fa fa-github fa-fw"></i>
            <span class="network-name">
              Github
            </span>
          </a>
        </li>
        <li>
          <a href="https://www.linkedin.com/in/davidwchristian/" class="btn btn-default">
            <i class="fa fa-linkedin fa-fw"></i>
            <span class="network-name">
              Linkedin
            </span>
          </a>
        </li>
      </ul>
    </div>
  </div><!-- end intro-wrapper -->
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Davidwchristian</title>

  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
  <body>
    <%= render 'layouts/sidebar' %>
    <div class="container">
      <%= render 'layouts/navbar' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/no-sidebar.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Davidwchristian</title>

  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
  <body>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/main/_portfolio.html.erb
<div class="center portfolio-arrow">
  <i class="fa fa-chevron-down fa-3x"></i>
</div>

<div class="row center portfolio-wrapper">
  <h1> 
    Portfolio 
  </h1>
  <hr class="intro-divider">
  
  <div class="portfolio-item">
    <%= image_tag 'dat-landscape.png' %>
    <p> 
      The Display Advertsing Technology Landscape
    </p>
  </div>

  <div class="portfolio-item">
     <%= image_tag 'dat-landscape.png' %>
     <p> 
      Display AdTech
     </p>
  </div>

  <div class="portfolio-item">
     <%= image_tag 'dat-landscape.png' %>
     <p> 
      Live It Up Social
     </p>
  </div>

  <div class="portfolio-item">

  </div>

  <div class="portfolio-item">

  </div>
  
  <div class="portfolio-item">

  </div>

</div>

app/views/main/portfolio.html.erb
<div class="portfolio-wrapper">
  <div class="portfolio-item">
    <h3> 
      <%= link_to @displayadtech, target: "_blank", :class =>"portfolio-item-header" do %>
        The Display Advertising Technology Landscape
      <% end %> 
      <br>
      <small> 
        Ruby on Rails, jmpress, HTML5, CSS3, JavaScript
      </small>
    </h3>
    <%= link_to @displayadtech, target: "_blank" do %>
      <div class="portfolio-item-image">
        <%= image_tag 'dat-landscape.png', :class => "flat-panel" %>
      </div>
    <% end %>
    <hr>
  </div><!-- end portfolio-item -->
  <div class="portfolio-item">
    <h3> 
      <%= link_to 'http://displayadtech.com', target: "_blank", :class =>"portfolio-item-header" do %>
        Display {AdTech}
      <% end %> 
      <br>
      <small> 
        Ruby on Rails, jmpress, AWS, HTML5, CSS3, JavaScript
      </small>
    </h3>
    <%= link_to 'http://displayadtech.com', target: "_blank" do %>
      <div class="portfolio-item-image">
        <%= image_tag 'display-adtech.png', :class => "flat-panel" %>
      </div>
    <% end %>
    <hr>
  </div><!-- end portfolio-item -->
  <!-- <div class="portfolio-item">
    <h3> 
      <%= link_to 'http://liveitupsocial.herokuapp.com/', target: "_blank", :class =>"portfolio-item-header" do %>
        Live It Up Social
      <% end %> 
      <br>
      <small> 
        Ruby on Rails, jmpress, HTML5, CSS3, JavaScript
      </small>
    </h3>
    <%= link_to 'http://liveitupsocial.herokuapp.com/', target: "_blank" do %>
      <div class="portfolio-item-image">
        <%= image_tag 'live-it-up.png', :class => "flat-panel" %>
      </div>
    <% end %>
    <hr>
  </div><!-- end portfolio-item --> 
</div><!-- end portfolio-wrapper -->

app/views/main/questionnaire.html.erb
<div class="center">
  <h1> Questionnaire </h1>
</div>

<section class="center">
  <%= render 'questionnaires/form' %>
<section>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="survey-input">
    <%= f.text_field :title, :class => "form-control features-input",
      :placeholder => 'title'
    %>
  </div>
  <div class="survey-input">
    <%= f.text_field :category,
      :class => "form-control features-input",
      :placeholder => 'category'  
    %>
  </div>
  <br>
  <div class="survey-input">
    <%= f.text_area :content, size: "60x5", :class => "form-control",
      :placeholder => 'content'  %>
  </div>
  <br>
  <div class="actions pull-left">
    <%= f.submit "FTW", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1 class="new-post"> New Post </h1>
<%= render 'posts/form' %>

app/views/posts/scope_chain.html.erb
<h1> Data Access and Scope Chain </h1>

app/views/questionnaires/_form.html.erb
<%= form_for @questionnaire do |f| %>
  <div class="survey-label">
    <p>
      Services used?
    </p>
  </div>
  <div class="survey-input">
    <%= f.radio_button :company, 'Wealthfront' %> 
    <%= label :company, 'Wealthfront' %>
    <%= f.radio_button :company, 'Betterment' %>
    <%= label :company, 'Betterment' %>
    <%= f.radio_button :company, 'Both' %>
    <%= label :company, 'Both' %>
  </div>
  <hr>

  <div class="survey-label">
    <p>
      Total Invested?
    </p>
  </div>
  <div class="survey-input">
    <%= f.radio_button :invested, ' > 10k' %> 
    <%= label :invested, '10k - 40k' %>
    <%= f.radio_button :invested, ' > 40k' %>
    <%= label :invested, ' > 40k' %>
    <%= f.radio_button :invested, ' > 70k' %>
    <%= label :invested, ' > 70k' %>
    <%= f.radio_button :invested, ' > 100k' %>
    <%= label :invested, ' > 100k' %>
    <%= f.radio_button :invested, ' > 200k' %>
    <%= label :invested, ' > 200k' %>
  </div>
  <hr>

  <div class="survey-label">
    <p>
      Age?
    </p>
  </div>
  <div class="survey-input" >
    <%= f.radio_button :age, '20 - 25' %> 
    <%= label :age, '20 - 25' %>
    <%= f.radio_button :age, '20 - 30' %>
    <%= label :age, '25 - 30' %>
    <%= f.radio_button :age, '30 - 35' %>
    <%= label :age, '30 - 35' %>
    <%= f.radio_button :age, '35 - 40' %>
    <%= label :age, '35 - 40' %>
    <%= f.radio_button :age, '40 - 45' %>
    <%= label :age, '40 - 45' %>
    <%= f.radio_button :age, '45 - 50' %>
    <%= label :age, ' > 55 ' %>
  </div>
  <hr>
  
  <div class="survey-label">
    <p> 
      How often do you visit your analytics Dashboard?
    </p>
  </div>
  <div class="survey-input">
    <%= f.radio_button :visits_desktop, 'Daily' %> 
    <%= label :visits_desktop, 'Daily' %>
    <%= f.radio_button :visits_desktop, 'Weekly' %>
    <%= label :visits_desktop, 'Weekly' %>
    <%= f.radio_button :visits_desktop, 'Monthly' %>
    <%= label :visits_desktop, 'Monthly' %>
  </div>
  <hr>

  <div class="survey-label">
    <p> 
      Mobile Dash?
    </p>
  </div>
  <div class="survey-input">
    <%= f.radio_button :visits_mobile, 'Daily' %> 
    <%= label :visits_mobile, 'Daily' %>
    <%= f.radio_button :visits_mobile, 'Weekly' %>
    <%= label :visits_mobile, 'Weekly' %>
    <%= f.radio_button :visits_mobile, 'Monthly' %>
    <%= label :visits_mobile, 'Monthly' %>
  </div>
  <hr>
  
  <div class="survey-label">
    <p> 
      Top areas/analytics you routinely check?
    </p>
  </div>
  <div class="survey-input">
    <%= f.text_field :features_visited_1, 
        :class => "form-control features-input",
        :placeholder => 'feature 1..'  
    %>
    <%= f.text_field :features_visited_2,
        :class => "form-control features-input",
        :placeholder => 'feature 2..'  
    %>
    <%= f.text_field :features_visited_3,
        :class => "form-control features-input",
        :placeholder => 'feature 3..'  
    %>
    <%= f.text_field :features_visited_4,
        :class => "form-control features-input",
        :placeholder => 'feature 4..?'  
    %>
    <%= f.text_field :features_visited_5,
        :class => "form-control features-input",
        :placeholder => 'feature 5..?'  
    %>
  </div>
  <hr>

  <div class="survey-label">
    <p>
      What analytics/features make you happy?
    </p>
  </div>
  <div class="survey-input">
    <%= f.text_field :delightful_features_1, 
      :class => "form-control features-input",
      :placeholder => 'feature 1..'  
    %>
    <%= f.text_field :delightful_features_2, 
      :class => "form-control features-input",
      :placeholder => 'feature 2..'
    %>
    <%= f.text_field :delightful_features_3, 
      :class => "form-control features-input",
      :placeholder => 'feature 3..'
    %>
    <%= f.text_field :delightful_features_4, 
      :class => "form-control features-input",
      :placeholder => 'feature 4..?'
    %>
    <%= f.text_field :delightful_features_5, 
      :class => "form-control features-input",
      :placeholder => 'feature 5..?'
    %>
  </div>
  <hr>

  <div class="survey-label">
    <p>
      Any features interupt your routine/flow?
    </p>
  </div>
  <div class="survey-input">
    <%= f.text_field :annoying_features_1,
      :class => "form-control features-input",
      :placeholder => 'feature 1..'  
    %>
    <%= f.text_field :annoying_features_2,
      :class => "form-control features-input",
      :placeholder => 'feature 2..'  
    %>
    <%= f.text_field :annoying_features_3,
      :class => "form-control features-input",
      :placeholder => 'feature 3..'  
    %>
    <%= f.text_field :annoying_features_4,
      :class => "form-control features-input",
      :placeholder => 'feature 4..?'  
    %>
    <%= f.text_field :annoying_features_5,
      :class => "form-control features-input",
      :placeholder => 'feature 5..?'  
    %>
  </div>
  <hr>

  <div class="survey-label">
    <p>
      Feature Requests? Anyting else?
    </p>
  </div>
  <div class="survey-input">
    <%= f.text_area :feature_requests, size: "60x5", :class => "form-control"  %>
  </div>
  <hr> 

  <div class="actions pull-left">
    <%= f.submit "Submit ..and thank you!", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/questionnaires/index.html.erb
<div class="survey-wrapper">
  <div class="center survey-title">
    <h1>
      <i class="fa fa-bar-chart"></i> 
      Results
    </h1>
    <hr>
  </div>

  <section class="center">
    <div class="survey-label">
      <p>
        Total Filled Out:
        <%= @questionnaires.length %>
      </p>
    </div>
    <hr>
    <% @questionnaires.each do |q| %>
    <div class="survey-label">
      <p>
        Company: <%= q.company %>
      </p>
      <p>
        Invested: <%= q.invested %>
      </p>
      <p>
        Age: <%= q.age %>
      </p>
      <p>
        Num Visits: <%= q.visits_desktop %>
      </p>
      <p>
        Num Mobile: <%= q.visits_mobile %>
      </p>
      <p>
        Routine:
      </p>
      <p>
        1.) <%= q.features_visited_1 %>
      </p>
      <p>
        2.) <%= q.features_visited_2 %>
      </p>
      <p>
        3.) <%= q.features_visited_3 %>
      </p>
      <p>
        4.) <%= q.features_visited_4 %>
      </p>
      <p>
        5.) <%= q.features_visited_5 %>
      </p>
      <p>
        Delightful Features:
      </p>
      <p>
        1.) <%= q.delightful_features_1 %>
      </p>
      <p>
        2.) <%= q.delightful_features_2 %>
      </p>
      <p>
        3.) <%= q.delightful_features_3 %>
      </p>
      <p>
        4.) <%= q.delightful_features_4 %>
      </p>
      <p>
        5.) <%= q.delightful_features_5 %>
      </p>
      <p>
        Annoying Features:
      </p>
      <p>
        1.) <%= q.annoying_features_1 %>
      </p>
      <p>
        2.) <%= q.annoying_features_2 %>
      </p>
      <p>
        3.) <%= q.annoying_features_3 %>
      </p>
      <p>
        4.) <%= q.annoying_features_4 %>
      </p>
      <p>
        5.) <%= q.annoying_features_5 %>
      </p>
      <p>
      Feature Requests: 
      <%= q.feature_requests %>
      </p>
    </div>
    <hr>
    <% end %>

    <div class="survey-input">
      
    </div>
    <hr>
     
  </section>
</div>

app/views/questionnaires/new.html.erb
<div class="survey-wrapper">
  <div class="center survey-title">
    <h1>
      <i class="fa fa-bar-chart"></i> 
      Dashboard Survey
    </h1>
    <hr>
  </div>

  <section class="center">
    <%= render 'questionnaires/form' %>
  </section>
</div>

app/views/questionnaires/results.html.erb
<div class="survey-wrapper">
  <div class="center survey-title">
    <h1>
      <i class="fa fa-bar-chart"></i> 
      Results
    </h1>
    <hr>
  </div>

  <section class="center">
    <%= render 'questionnaires/form' %>
  </section>
</div>

app/views/questionnaires/show.html.erb
<div class ="center"> 
  <h1 style="margin: 150px 0">
    Thank You!
  </div>
</div>